### ISSUE TITLE
Stream support when reading large LAZ files from S3 or HDFS.

### ISSUE THREAD

**Issue by romulogoncalves** [geotrellis/geotrellis-pointcloud#10]
It seems it is not to be possible to read large LAS/LAZ files. 

We just tried to read a 2.5GB and we got:
```
 java.lang.RuntimeException: Cannot read path hdfs://ecolidar0.eecolidar-nlesc.surf-hosted.nl:9000/user/hadoop/C_25GN2.laz because it's too big...
	at scala.sys.package$.error(package.scala:27)
```

We could cute the file with GDAL before uploading it to our local S3, but if we could stream such large files directly from S3 it would be great. The data sets we have are countrywide LiDAR data sets where each file (LAZ format) can reach 4GB size. 

I think the issue could be solved in a similar way to what [GeoTrellis did for large GeoTiffs](https://github.com/locationtech/geotrellis/issues/1627).

**Comment by pomadchin** [comment]
Hey @romulogoncalves we're reading `las` and `laz` files via `PDAL` and not via our LAS / LAZ readers, i believe it's a good question for a PDAL gitter channel!

**Comment by pomadchin** [comment]
Some references: https://pdal.io/pipeline.html#processing-modes and https://pdal.io/apps/pipeline.html#pipeline-command 

If you could investigate a little bit more - where the problem happens, or to provide some test data to track it down it would be useful.

**Comment by pomadchin** [comment]
By "where" i mean is it a `PDAL` issue or `PDAL bindings` issue or `GeoTrellis pointcloud` issue.

**Comment by pomadchin** [comment]
Ah potentially the issue is [here](https://github.com/geotrellis/geotrellis-pointcloud/blob/master/src/main/scala/geotrellis/pointcloud/spark/io/hadoop/formats/PointCloudInputFormat.scala#L117-L120) can you double check it?

**Comment by romulogoncalves** [comment]
@pomadchin I will check it, thanks.

btw, the data can be obtained from here:
https://geodata.nationaalgeoregister.nl/ahn3/extract/ahn3_laz/C_25GN2.LAZ

**Comment by romulogoncalves** [comment]
I think the error comes from GeoTrellis. When you search for the error message you find the following [line of code at HdfsUtls.scala](https://github.com/locationtech/geotrellis/blob/f5601fb50bc9afa2863b7a128b5565d7adf24a96/spark/src/main/scala/geotrellis/spark/io/hadoop/HdfsUtils.scala#L166)
``` 
def readBytes(path: Path, conf: Configuration): Array[Byte] = {
    val fs = path.getFileSystem(conf)

    val len =
      fs.getFileStatus(path).getLen match {
        case l if l > Int.MaxValue.toLong =>
          sys.error(s"Cannot read path $path because it's too big...")
        case l => l.toInt
}
```
I think it doesn't even reaches PDAL at this points looking to the backtrace:
```
	at scala.sys.package$.error(package.scala:27)
	at geotrellis.spark.io.hadoop.HdfsUtils$.readBytes(HdfsUtils.scala:164)
	at geotrellis.spark.io.hadoop.formats.BinaryFileRecordReader.initialize(BinaryFileInputFormat.scala:32)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:189)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:186)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:141)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:70)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pomadchin** [comment]
Thx for investigation! The thing is that `PDAL` can work only with local files, so we need to fix the current logic of copying file from `HDFS` / `S3` to a local fs to prevent this exception.

**Comment by romulogoncalves** [comment]
Are these files removed from the `/tmp/` dir after pipeline execution? We are running out of space after running several pipelines within the same application.

What is the effect of `RDD.cache()` or `RDD.unpersist()` on these temporary copies of the LAS files?

**Comment by pomadchin** [comment]
@romulogoncalves both questions are good, i'll double check the deletion of las / laz files;
`cache` caches in memory be default, in fact it's an extra copy of rdd in mem / on disk (depending on the strategy you want to follow). it's required sometimes to speed up computations in cases when you need to do several things to the same rdd starting from some logical point.

**Comment by pomadchin** [comment]
tmp files should be deleted: https://github.com/geotrellis/geotrellis-pointcloud/blob/master/src/main/scala/geotrellis/pointcloud/spark/io/hadoop/formats/PointCloudInputFormat.scala#L179-L180

**Comment by romulogoncalves** [comment]
That's good news, but then how are things managed when the pipeline touches a lot of files? We do a crop to reduce data size, but in reality it does matter much for the size of `/tmp/` because all files on which the polygon touches are downloaded and kept until the end of the pipeline execution, right?

To circumvent the issue we could have these files stored in a different location, such as `/scratch/`, and not the default systems `/tmp/` dir. Is that configurable?

Despite the data is kept around, are files re-used? We just run the following job which reads 4 LAZ files from a HDFS dir, crops them, calculates Hag and then stores the result in RDD for further inspection (we use Jupyter notebooks btw):
```
val laz_path = new Path("/user/hadoop/ahn3/small_data/*.laz")
val polygon_str :Option[String] = Option("POLYGON ((131000.0 485000.0, 131000.0 492000.0, 135000.0 492000.0, 135000.0 485000.0, 131000.0 485000.0))")

val pipelineExpr = Read("local") ~ CropFilter(polygon = polygon_str) ~ HagFilter()
val rdd_laz = HadoopPointCloudRDD(laz_path, options = HadoopPointCloudRDD.Options(pipeline = pipelineExpr))

val points :RDD[Array[(Double, Double, Double, Double)]] = rdd_laz.flatMap(_._2).mapPartitions{ _.map { packedPoints =>
  var res = new Array[(Double, Double, Double, Double)](packedPoints.length)
  cfor(0)(_ < packedPoints.length, _ + 1) { i =>
    res(i) = (packedPoints.getX(i), packedPoints.getY(i), packedPoints.getZ(i), packedPoints.getDouble(i, dim = "HeightAboveGround"))
  }
  res
}}

//To trigger the execution
points.flatMap(m => m).count()
```

For our surprise we see duplicate files on each node, here how the `/tmp/` dir of one of the nodes looks like after a execution (the `/tmp/` dir was cleaned before running the job):
```
/tmp/spark-602e00e9-9440-4f5a-878d-8dcb0730f403:
C_25HN1.laz

/tmp/spark-8221aab1-6e16-4426-89b6-7cd610120646:
C_25HN1.laz

/tmp/spark-cb3741a0-2cf2-4f42-b3d4-7f626fe8ffd0:
C_25FZ2.laz

/tmp/spark-e05fc0c5-c8f3-427f-a96e-bd453430ea40:
C_25FZ2.laz
```

If we are missing something, please let us know. If more info is required we are happy to provide it.

**Comment by pomadchin** [comment]
Right, yes you can set it up [to any dir you want](https://github.com/geotrellis/geotrellis-pointcloud/blob/master/src/main/scala/geotrellis/pointcloud/spark/io/hadoop/formats/PointCloudInputFormat.scala#L70-L71): 

```scala
// it's a mutable operation, mutates config object here
PointCloudInputFormat.setTmpDir(conf, "/scratch/")
```

Well it can happen so, if any node would require data from the same file than it would be downloaded.  To avoid it you need to be sure that in your partitioning scheme you have a single file per executor and each executor works only with data from local files.

**Comment by pomadchin** [comment]
The discussion started here would be continued in this issue: https://github.com/geotrellis/geotrellis-pointcloud/issues/12

**Comment by MahdiSMIDA** [comment]
may be reading las files with IQMULUS will be a good idea

**Comment by pomadchin** [comment]
@MahdiSMIDA their Spark lib is outdated https://github.com/IGNF/spark-iqmulus and supports only las / laz files. PDAL allows to generalize reading and support other pointcloud data formats.
