### ISSUE TITLE
Type Mismatch: ArrayTile and DoubleArrayTile.

### ISSUE THREAD

**Issue by romulogoncalves** [geotrellis/geotrellis-pointcloud#15]
Hi, 

We are now loading geotrellis-pointcloud code into IntelIJ and we got complains about a type mismatch in [TrianglesRasterizer](https://github.com/geotrellis/geotrellis-pointcloud/blob/master/src/main/scala/geotrellis/pointcloud/raster/rasterize/triangles/TrianglesRasterizer.scala#L33) because an `DoubleArrayTile` is created when the return type is `ArrayTile`.

If we change the return to `DoubleArrayTile` we still have the issue with `MutableArrayTile` when calling `apply`. How such issue was circumvented on your IDE setup?

**Comment by pomadchin** [comment]
`DoubleArrayTile` [is a subtype of `MutableArrayTile`](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/DoubleArrayTile.scala#L24-L25) which [is a subtype of an `ArrayTile`](https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/MutableArrayTile.scala#L28) should work fine as it is.

What Intelij IDEA version are you on? 
I don't have a special setup, just a Scala plugin, also don't trust Scala syntax highlight too much in intelij.

**Comment by romulogoncalves** [comment]
Solved, the order of compilation was creating this issue. It also needed `geotrellis-vector` 1.2 since the 1.1 does not have triangulation.
