### ISSUE TITLE
Test PDAL triangulation services

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/geotrellis-pointcloud#29]
Using a PDAL pipeline definition, we can generate Delaunay triangulations from a point cloud.  We will source the data for this operation from the EPT files generated in #28.  Pick an arbitrary AOI for the sample data set and run the pipeline using the PDAL CLI.

Our objective is to have areference pipeline that we can use with a RasterSource.

**Comment by pomadchin** [comment]
Was closed by @jpolchlo and merged in https://github.com/geotrellis/geotrellis-pointcloud/blob/master/pointcloud/src/main/scala/geotrellis/pointcloud/raster/ept/DEMRasterSource.scala#L89
