### ISSUE TITLE
Implement PDALRasterSource

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/geotrellis-pointcloud#30]
Starting from a path to some EPT catalog, we want to read a DEM raster for a given AOI.  This task assumes that it is not possible to read a DEM that is generated directly by PDAL from memory (we assume that the PDAL DEM sink works directly to disk, and there is no internal API to work with their rasters).

Implement this RasterSource in this repo.

[Estimated 5 point task]

**Comment by echeipesh** [comment]
Resolved by: https://github.com/geotrellis/geotrellis-pointcloud/pull/40
