### ISSUE TITLE
Rasterize a PDAL Mesh

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/geotrellis-pointcloud#32]
Following completion of #31, we will have access to meshes from PDAL.  These need to be rasterized to a DEM format.  This will either involve iterating over the PDAL structure directly or conversion to a `geotrellis.vector.mesh` object prior to using existing rasterization code.

[Estimated 5 point task]

**Comment by pomadchin** [comment]
Closed in https://github.com/geotrellis/geotrellis-pointcloud/issues/32
