### ISSUE TITLE
Evaluate performance of PDALRasterSource

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/geotrellis-pointcloud#33]
Once #30 is complete, we will need to consider its performance.  If it is sufficient, then :tada:, else we will need to consider optimizations, up to and inluding
- Truncating the point stream to meet some QOS requirement
- Using GT's triangulator
- Something else

**Comment by pomadchin** [comment]
I'm wondering, was it covered by https://github.com/geotrellis/geotrellis-pointcloud/issues/37 in general or if it was covered only partially? Mb it makes sense to create more specific issues and to close this one?

**Comment by pomadchin** [comment]
Closed in https://github.com/geotrellis/geotrellis-pointcloud/pull/55
