### ISSUE TITLE
pom.xml still points to pdal 1.6.0

### ISSUE THREAD

**Issue by romulogoncalves** [geotrellis/geotrellis-pointcloud#5]
The pom file at:
http://dl.bintray.com/azavea/geotrellis/

Still points to pdal-scale 1.6.0
<groupId>io.pdal</groupId>
<artifactId>pdal-scala_2.11</artifactId>
<version>1.6.0</version>

While the README re-directs us to PDAL/java which for versions > 1.7.0

Is there plans to align the versions? 
Is also there plans to make it available at the maven repository?

**Comment by pomadchin** [comment]
Hey @romulogoncalves yes, we'll update this demo soon (and fix tests). 
_Not sure_ how it would go with maven central, but definitely would be published on bintray.

**Comment by pomadchin** [comment]
Also PDAL/java works fine for PDAL 1.4+, and the docs should be the same. The story is that PDAL/java moved from the PDAL/PDAL repo folder into its separate repository.

**Comment by romulogoncalves** [comment]
Thanks,

In the meantime I am using it with PDAL 1.7-maintainance and I use pdal-scala 1.7.1 jars and so it works without issues.

**Comment by pomadchin** [comment]
Fixed in #7

**Comment by pomadchin** [comment]
Hey! geotrellis-pointcloud has auto publish to bintray already: https://bintray.com/azavea/geotrellis/geotrellis-pointcloud/0.2-82cb0fb check out the new version!
