### ISSUE TITLE
Test PDALRasterSource on full scale 3DEP regions

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-pointcloud#57]
Ref: https://usgs.entwine.io/

This issue is to point geotrellis-server + PDALRasterSource at 3DEP  and explore the performance and behavior on a large data set. The outcome of this issue is a demo and a list of areas or conditions under which issues were encountered.

- [x] [Point GeoTrellis-Server at 3DEP on S3](https://github.com/geotrellis/geotrellis-pointcloud-server/blob/master/src/main/resources/application.conf#L225-L262)
- [ ] Explore various regions (3+)
- [ ] Document issues or artifacts or performance concerns encountered

**Comment by jpolchlo** [comment]
I was able to point https://github.com/geotrellis/geotrellis-pointcloud-server at 3DEP sources on S3.  These required the `application.conf` to be modified (or a separate conf file can be provided at runtime as a --conf argument) to point to sources in the s3://usgs-lidar-public/ bucket (the AWS_REGION environment variable needs to be set to `us-west-2` for this to work).

No notable performance issues were encountered beyond issues that were present in small-scale local tests.

Example images produced from S3-hosted EPT trees can be seen in #64.
