### ISSUE TITLE
PointCloud.getShort(i, dim = "Classification") gives java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by romulogoncalves** [geotrellis/geotrellis-pointcloud#6]
Hi,

I have a cluster (Spark 2.2.0 and Hadoop 2.8.3) with 4 Ubuntu 16.4 nodes (2 cores and 8GB each). To have geotrellis-pointcloud I use the following jars:
geotrellis-pointcloud 1.6.0
io.pdal:pdal                1.7.1
io.pdal:pdal_scala        1.7.1
io.pdal:pdal_native      1.7.1

The installed PDAL is version 1.7.maintenance, installed from sources.

When I read X, Y, Z into a RDD[(Double, Double, Double)] and I take the first 10 points it works without issues. When I try to also read Classification it crashes.

Here are the details to reproduce the problem. We are using a LAZ file with 24487575 points, [link to download it](https://geodata.nationaalgeoregister.nl/ahn3/extract/ahn3_laz/C_25EZ2.LAZ). The file was uploaded to HDFS and we use the following code to read the data into a **:RDD[(Double, Double, Double, Short)]**, i.e., RDD[X, Y, Z, Classification]
```
val laz_path = new Path("/user/hadoop/ahn3/C_25EZ2.laz")
val rdd_laz = HadoopPointCloudRDD(laz_path)

val points :RDD[(Double, Double, Double, Short)] = rdd_laz.flatMap(_._2).mapPartitions{ _.map { packedPoints =>
  var res = new Array[(Double, Double, Double, Short)](packedPoints.length)
  cfor(0)(_ < packedPoints.length, _ + 1) { i =>
    res(i) = (packedPoints.getX(i), packedPoints.getY(i), packedPoints.getZ(i), packedPoints.getShort(i, dim = "Classification"))
  }
  res
}}.flatMap( m => m)
```

Then I ask for the first 10 points with a take
```
val points10 = points.take(10)
```

I get the following error:
```
Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Task 0 in stage 57.0 failed 4 times, most recent failure: Lost task 0.3 in stage 57.0 (TID 95, 145.100.58.116, executor 3): java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310)
	at io.pdal.PointCloud.getShort(PointCloud.scala:91)
	at $line496.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$2$$anonfun$apply$1.apply(<console>:98)
	at $line496.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$2$$anonfun$apply$1.apply(<console>:95)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
```

**Comment by pomadchin** [comment]
Hey! I'll try to have a look into it as fast as it's possible. Thanks for your report!

**Comment by romulogoncalves** [comment]
We spot the reason, we should use getByte and not getShort. In the schema I got confuse with Intensity which is a 2 byte field while classification is 1 byte.

I think we can mark it invalid, right?

**Comment by pomadchin** [comment]
Yea, if it's the case than feel free to close your issue. :D Glad that it was just a type mismatch.

**Comment by romulogoncalves** [comment]
Issue is invalid, there was a type mismatch.
