### ISSUE TITLE
Make use of an OverviewStrategy in the DEMRasterSources implementation

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-pointcloud#62]
At this point `DEMRasterSources` don't use `OverviewStrategy` and rely only on the `PDAL` `EPTReader` capabilities https://github.com/PDAL/PDAL/blob/2.1.0/io/EptReader.cpp#L293-L318. 

This task is to improve control over it to improve real time performance.

The core use case is to be able to select the actual resolution we're querying from the EPT tree.

- Use OverviewStrategy to select the PDAL resolution
- Treat the RasterSource `cellSize` as request into GT `OverviewStrategy` given resolutions computed from metadata
- Use returned resolution as query parameter to PDAL Pipeline

Requires: https://github.com/geotrellis/geotrellis-pointcloud/issues/69

**Comment by echeipesh** [comment]
Change in `EPTRasterSourceProvider`

Use case: 
We get a WCS request is for 30x30m resolution, we want to query the EPT through PDAL pipeline at at 60x60m resolution:

`ept://path/to/catalog?overviewStrategy=auto-2`
