### ISSUE TITLE
Fix the resolutions response from DEM RasterSources

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/geotrellis-pointcloud#69]
While messing around with QGIS via https://github.com/geotrellis/geotrellis-pointcloud-server, I noticed something funny with the DEM raster sources is going on.  Observe zooming in on the Red Rocks data:

![far](https://user-images.githubusercontent.com/18410961/78067709-2a7dcc80-7365-11ea-9570-8cc6c6d45a79.png)
![near](https://user-images.githubusercontent.com/18410961/78067787-4da87c00-7365-11ea-9c9a-2cd531dfc304.png)

In the second image, it's clear to see that the pixels appear to have gotten larger, implying that the gridExtent of the requests aren't updating to the new view parameters.  It looks from the source like the gridExtent being used everywhere in DEMRasterSource (soon to be TINRasterSource) is simply being pulled from the EPTMetadata.  I could be missing something, but the behavior suggests that at least something like this is happening.  We need to investigate.

**Comment by pomadchin** [comment]
Will add some extra context, GeoTrellis PointCloud logs all the requested scenes. During the WCS zoom in operation QGIS always sends the same request:

```
 /?SERVICE=WCS&VERSION=1.1.1&REQUEST=GetCoverage
...
GRIDOFFSETS=-0.00006233669818305%2C0.00008030763819988
```

Where `GRIDOFFSETS=-0.00006233669818305%2C0.00008030763819988` is the requested resolution. 

WMS and WMTS properly handle zoom requests (this can actually be also an explanation why WCS is so much faster).

**Comment by jpolchlo** [comment]
That's a good observation, and it implies that we need a proper resolution list to be supplied in the GetCapabilites request.

**Comment by pomadchin** [comment]
https://github.com/geotrellis/geotrellis-pointcloud-server/commit/81b545c7794c998397648bd181acfbb59e28366b 💯

**Comment by pomadchin** [comment]
![image](https://user-images.githubusercontent.com/4929546/78715150-f8331880-78ea-11ea-8c98-c3576afcffb7.png)

And all WCS requests work correct now.
